---
- name: reload pm2 poller
  become: true
  become_user: "{{ rs_user }}"
  command: pm2 reload {{ pm2_poller_name }}
  environment:
    HOME: "{{ rs_home }}"

- name: reload pm2 nodered
  become: true
  become_user: "{{ rs_user }}"
  command: pm2 reload {{ pm2_nodered_name }}
  environment:
    HOME: "{{ rs_home }}"

- name: save pm2
  become: true
  become_user: "{{ rs_user }}"
  command: pm2 save
  environment:
    HOME: "{{ rs_home }}"
  listen: reload pm2 poller
